languageCode = "zh-cn"
languageName = "Simplified Chinese (China)"
weight = 1
# title = "Edison Chen"

[params]
  displayName = "中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo-1.png"
  # secondaryLogo = "img/Edisoncat_logo.png" # 这个 logo 的颜色方案应该是和上面的是相反或对比的。
  # description = "一个强大、轻量级的 Hugo 主题。"

[params.author]
  name = "Edison Chen"
  image = "img/logo.png"
  # headline = "一名热爱学习的设计初学者"
  bio = "一名热爱学习的设计初学者"
  links = [
    { email = "mailto:cs785745156@gmail.com" }, 
    { douyin = "https://v.douyin.com/iynBcrrn/ 8@4.com :9pm" },
    { github = "https://github.com/Eeedisonc/Eeedisonc.github.io" },
    { x-twitter = "https://x.com/EDC_555" },
  ]