# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "文档"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "简介"
  pageRef = "resume"
  weight = 20

[[main]]
  name = "工具"
  weight = 30

[[main]]
  name = "photoshop"
  parent = "工具"
  pageRef = "工具"
  weight = 25

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 40

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

[[main]]
  identifier = "email"
  pre = "email"
  url = "mailto:cs785745156@gmail.com"
  weight = 200

#[[main]]
#  identifier = "douyin"
#  pre = "douyin"
#  url = "https://v.douyin.com/iynBcrrn/ 8@4.com :9pm"
#  weight = 300

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://Eeedisonc.github.io"
  weight = 400

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/EDC_555"
  weight = 500

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "标签"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "作者"
   pageRef = "authors"
   weight = 20